apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  selector:
    matchLabels:
      name: api-app
  replicas: 1
  template:
    metadata:
      labels:
        name: api-app
    spec:
      containers:
      - name: api-app
        image: shiota2021/epoch-sample-api:master.20220419-173459
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: "development"
        - name: API_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8

---
apiVersion: v1
kind: Service
metadata:
  name: api-app
  labels:
    name: api-app-bluegreen-active
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31002
  selector:
    name: api-app

